apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-emln
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-emln
    app.kubernetes.io/part-of: mc-unsupported-runtime
  name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-emln
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-emln
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-emln
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-olum-tenant/mc-unsupported-runtime/devfile-sample-python-basic-rhtap-mc-unsuported-runtime-emln@sha256:504257af438f54f5e3167518024578c39f8a44d0d74ff31916d5ccd23613656c
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
